### PR TITLE
Update wire-compiler to 1.8.0

### PR DESCRIPTION
**Pull request by EddieRingle**
Signed-off-by: Eddie Ringle eddie@ringle.io

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks. There's a lot to do here before we publish, but plans are in motion.

**Comment by EddieRingle** [comment]
@JakeWharton I was just about to submit a PR to add the maven plugin so that, at the very least, JitPack can build this repo. Would that be alright?

**Comment by JakeWharton** [comment]
The maven plugin is in the main repo so no need.

**Comment by JakeWharton** [comment]
Oh you mean the maven gradle plugin. That's probably fine...

**Pull request merged**
